modLoader="javafml" #mandatory

loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="ariabase" #mandatory

version="1.16.1-0.0.1" #mandatory

displayName="Aria Base" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="http://example.com/" #optional

logoFile="examplemod.png" #optional

credits="Thanks to the FML team and to TechnoVision for their great tutorials" #optional

authors="RS_Mind" #optional

description='''
The base mod for the Aria mod collection.
'''

[[dependencies.examplemod]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[31,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
